### ISSUE TITLE
PHP Fatal error getimagesize

### ISSUE THREAD

**Issue by onecooltaco** [cronkite-asu/Cronkite-News-bootstrap#3]
In the logs I am seeing the following errors:

```
PHP Fatal error:  Uncaught TypeError: getimagesize(): Argument #1 ($filename) must be of type string, array given
PHP Fatal error:  Uncaught TypeError: getimagesize(): Argument #1 ($filename) must be of type string, array given in Cronkite-News-bootstrap/partials/content-long-form-noticias.php:645
``` 

This is causing a fatal PHP error on multiple pages that use these templates.

Here are some example pages that cause this to happen:

* https://cronkitenews.azpbs.org/2023/03/28/skateboard-forever-stamps-usps-navajo-artist-diorr-greenwood/
* https://cronkitenews.azpbs.org/2023/02/23/organizacion-sin-fines-de-lucro-apoya-a-mujeres-latinas-emprendedoras-en-arizona-brindandoles-una-espacio-en-sus-mercados-mensuales/

**Comment by cosmoonot** [comment]
Issue has been resolved.
